# Testing the gine model with the PCQMv2 dataset on IPU.
constants:
  name: &name neurips2023_large_data_gine
  config_override: "expts/neurips2023_configs/config_large_gcn.yaml"

architecture:
  pre_nn_edges:   # Set as null to avoid a pre-nn network
    out_dim: 32
    hidden_dims: 128
    depth: 2
    activation: relu
    last_activation: none
    dropout: 0.1
    normalization: &normalization layer_norm
    last_normalization: *normalization
    residual_type: none

  gnn:  # Set as null to avoid a post-nn network
    out_dim: &gnn_dim 704
    hidden_dims: *gnn_dim
    layer_type: 'pyg:gine' #pyg:gine #'pyg:gps' # pyg:gated-gcn, pyg:gine,pyg:gps

  graph_output_nn:
    graph:
      out_dim: *gnn_dim
      hidden_dims: *gnn_dim
    node:
      out_dim: *gnn_dim
      hidden_dims: *gnn_dim

trainer:
  logger:
    name: *name
    project: *name
  model_checkpoint:
    dirpath: models_checkpoints/neurips2023-large-gine/
    filename: *name
