name: doc

on:
  push:
    branches: ["main"]
  release:
    types: [published]

jobs:
  doc:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          environment-name: openfractal
          cache-environment: true
          cache-downloads: true

      - name: Install library
        run: python -m pip install --no-deps .

      - name: Deploy the doc
        run: |
          echo "Configure git"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          echo "Get the gh-pages branch"
          git fetch origin gh-pages

          TAG_OR_BRANCH_NAME=${GITHUB_REF##*/}

          if [ $TAG_OR_BRANCH_NAME = "main" ]; then
            echo "Build and deploy the doc on main"
            mike deploy --push --force main
          else
            echo "Build and deploy the doc on $TAG_OR_BRANCH_NAME"

            mike deploy --push --force stable
            mike deploy --push --force $TAG_OR_BRANCH_NAME
          fi
