constants:
  seed: &seed 42
  raise_train_error: true   # Whether the code should raise an error if it crashes during training

datamodule:
  module_type: "DGLOGBDataModule"
  args:
    cache_data_path: null
    dataset_name: "ogbg-molbace"
    cache_data_path: goli/data/cache/ogb-molbace/full.cache

    # Weights
    weights_type: null

    # Featurization
    featurization_n_jobs: -1
    featurization_progress: True
    featurization:
      atom_property_list_onehot: [atomic-number, valence]
      atom_property_list_float: [mass, electronegativity, in-ring, hybridization, chirality, aromatic, degree, formal-charge, single-bond, double-bond, radical-electron, vdw-radius, covalent-radius, metal]
      edge_property_list: [bond-type-onehot, bond-type-float, stereo, in-ring, conjugated, estimated-bond-length]
      add_self_loop: False
      explicit_H: False
      use_bonds_weights: False
      pos_encoding_as_features: &pos_enc
        pos_type: laplacian_eigvec
        num_pos: 3
        normalization: "none"
        disconnected_comp: True
      pos_encoding_as_directions: *pos_enc

    # Train, val, test parameters
    batch_size_train_val: 256
    batch_size_test: 256

  # Data loading
  num_workers: 4
  pin_memory: False
  persistent_workers: True  # Keep True on Windows if running multiple workers


trainer:
  trainer:
    gpus: 1

    