constants:
  seed: &seed 42
  raise_train_error: true   # Whether the code should raise an error if it crashes during training

datamodule:
  module_type: "DGLOGBDataModule"
  args:
    cache_data_path: null
    dataset_name: "ogbg-molpcba"
    cache_data_path: goli/data/cache/ogb-molpcba/full-morefeatures.cache

    # Weights
    weights_type: null
    sample_size: null

    # Featurization
    featurization_n_jobs: 8
    featurization_progress: True
    featurization:
      atom_property_list_onehot: [atomic-number, valence]
      atom_property_list_float: [mass, electronegativity, in-ring, hybridization, chirality, aromatic, degree, formal-charge, single-bond, double-bond, radical-electron, vdw-radius, covalent-radius, metal]
      edge_property_list: [bond-type-onehot, bond-type-float, stereo, in-ring, conjugated, bond-length]
      add_self_loop: False
      explicit_H: False
      use_bonds_weights: False
      pos_encoding_as_features: &pos_enc
        pos_type: laplacian_eigvec
        num_pos: 3
        normalization: "none"
        disconnected_comp: True
      pos_encoding_as_directions: *pos_enc

    # Train, val, test parameters
    batch_size_train_val: 2048
    batch_size_test: 2048

  # Data loading
  num_workers: 8
  pin_memory: False
  persistent_workers: True  # Keep True on Windows if running multiple workers


architecture:
  model_type: fulldglnetwork
  pre_nn:   # Set as null to avoid a pre-nn network
    out_dim: &hidden_dim 360
    hidden_dims: *hidden_dim
    depth: 1
    activation: relu
    last_activation: none
    dropout: &dropout 0.1
    batch_norm: &batch_norm True
    last_batch_norm: *batch_norm
    residual_type: none

  gnn:  # Set as null to avoid a post-nn network
    out_dim: *hidden_dim
    hidden_dims: *hidden_dim
    depth: 4
    activation: none
    last_activation: none
    dropout: *dropout
    batch_norm: *batch_norm 
    last_batch_norm: *batch_norm
    residual_type: simple
    pooling: sum
    virtual_node: 'none'
    layer_type: 'dgn-msgpass'
    layer_kwargs:
      # num_heads: 3
      aggregators: [mean, max, sum, min, dir1/dx_abs, dir1/smooth]
      scalers: [identity]
  
  post_nn:
    out_dim: 128
    hidden_dims: *hidden_dim
    depth: 1
    activation: relu
    last_activation: sigmoid
    dropout: *dropout
    batch_norm: *batch_norm
    last_batch_norm: False
    residual_type: none

predictor:
  metrics_on_progress_bar: ["mae", "averageprecision", "f1 > 0.5"]
  loss_fun: bce
  random_seed: *seed
  optim_kwargs:
    lr: 5.e-3
    weight_decay: 0
  lr_reduce_on_plateau_kwargs:
    factor: 0.5
    patience: 20
    min_lr: 1.e-4
  scheduler_kwargs:
    monitor: &monitor averageprecision/val
    mode: &mode max
    frequency: 1
  target_nan_mask: 0 # null: no mask, 0: 0 mask, ignore: ignore nan values from loss


metrics:
  - name: mae
    metric: mae
    threshold_kwargs: null

  - name: averageprecision
    metric: averageprecision
    threshold_kwargs:
      threshold: null
      th_on_preds: False
      th_on_target: False
      target_to_int: True

  - name: auroc
    metric: auroc
    threshold_kwargs:
      threshold: null
      th_on_preds: False
      th_on_target: False
      target_to_int: True

  - name: f1 > 0.5
    metric: f1
    num_classes: 2
    average: micro
    threshold_kwargs: &threshold_1
      operator: greater
      threshold: 0.5
      th_on_preds: True
      th_on_target: False
      target_to_int: True

  - name: f1 > 0.25
    metric: f1
    num_classes: 2
    average: micro
    threshold_kwargs: &threshold_2
      operator: greater
      threshold: 0.25
      th_on_preds: True
      th_on_target: False
      target_to_int: True

  - name: recall > 0.5
    metric: recall
    threshold_kwargs: *threshold_1

  - name: recall > 0.25
    metric: recall
    threshold_kwargs: *threshold_2

trainer:
  logger:
    save_dir: logs/ogb-molpcba
  early_stopping:
    monitor: *monitor
    min_delta: 0
    patience: 80
    mode: *mode
  model_checkpoint:
    dirpath: models_checkpoints/ogb-molpcba/
    filename: "bob"
    monitor: *monitor
    mode: *mode
    save_top_k: 1
    period: 1
  trainer:
    max_epochs: 1000
    min_epochs: 100
    gpus: 1

    